Feature/oprod
lattice/quda pull request #1007
Opened 2020-06-03 17:52 UTC by maddyscientist

This pull request is mainly clean up pull, but also will give some small boosts in MILC performance. 
* Cleanup of the outer-product routines to use `colorspinor` accessors instead of the legacy textures accessors.  Still much optimization to be done for these routines, but this can wait until multi-RHS support is present in QUDA.
* Removal of legacy functions that are no longer used.
* Fix for latent race condition in `cudaColorSpinorField::exchangeGhost`: function does not return until any outstanding P2P sending is complete.
* Staggered outer product kernel now uses the regular `exchangeGhost` function for improved scaling.
* `GaugeField::fat_link_max` is now not computed until it is needed, as opposed to doing it whenever a fat-link host field is created.  This means we can do this evaluation on the device as opposed to the host, the end result is more than a halving in time spent in `loadGaugeQuda` when running using MILC.

This cleanup and optimization has been verified against MILC RHMC.

2020-06-03 18:16 UTC, weinbe2 commented
Has this been tested against Chroma HMC? I see the clover outer product routines were also updated.

2020-06-03 18:16 UTC, maddyscientist commented
No, because Chroma doesn't use QUDA for anything other than the solver.

2020-06-03 18:18 UTC, weinbe2 commented
What correctness testing has been/should be done for the clover changes otherwise?

2020-06-03 18:20 UTC, maddyscientist commented
We don't have any tests off-hand that use this any more.  This code was used by the old TIFR MILC clover RHMC code, but that's not used in production any more.  For now, these routines are kept around for if / when we have HMC natively in QUDA.

2020-06-03 18:24 UTC, weinbe2 commented
I'm not pleased by the idea that we have this code exposed in the interface if we don't have active testing/verification, but I guess it's not unprecedented re:the issues in gauge fixing code, if I remember correctly.

I won't hold up the PR for it, but please file an issue/feature request for it (if there isn't one already) so we have it recorded somewhere.

2020-06-03 18:25 UTC, maddyscientist commented
Long outstanding issue: https://github.com/lattice/quda/issues/164

2020-06-03 19:03 UTC, mathiaswagner commented
Do we need to clang-format this? Just thought of it and might forget later.

2020-06-03 19:48 UTC, maddyscientist commented
> Do we need to clang-format this? Just thought of it and might forget later.

I already did.

2020-06-04 03:40 UTC, weinbe2 approved these changes
Gave this a visual inspection and did a due-diligence build+link with MILC, all looks good.

2020-06-04 05:12 UTC, mathiaswagner requested changes
Looks good. MILC test also looked fine.

2020-06-04 05:12 UTC, mathiaswagner commented on include/color_spinor.h
> +        // out(j,i) = a(0,j) * conj(b(0,i));
can this be deleted?

2020-06-04 12:35 UTC, merged