fix some issues with tests
lattice/quda pull request #1225
Opened 2021-12-15 17:56 UTC by jcosborn

2021-12-15 17:56 UTC, mathiaswagner commented
Jenkins: Can one of the admins verify this patch?

2021-12-15 18:22 UTC, mathiaswagner commented
@Jenkins please test this.

2021-12-16 07:35 UTC, mathiaswagner commented
@Jenkins ok to test.

2021-12-16 22:14 UTC, maddyscientist commented on tests/staggered_dslash_test_utils.h
> +      printfQuda("Results: CPU=%f, CUDA=%f, (CPU-CUDA)/CPU=%e\n", spinor_ref_norm2, cuda_spinor_out_norm2, 1.0-cuda_spinor_out_norm2/spinor_ref_norm2);
@jcosborn can you apply this change to dslash_test_utils.h.  Despite the fact it arose due to a misunderstanding, it's a good change to have.  Though I think it probably would be better to have `1.0 - sqrt(....)`

2021-12-16 23:29 UTC, maddyscientist commented on tests/invert_test.cpp
> +    mg_param.invert_param = &inv_param;
This changes breaks the MG solver when run through invert_test.  This is primarily due to the poor interface of the multigrid solver, but it is what it is.  The reasoning is that the `QudaInvertParam` that is embedded in the `QudaMultigridParam` is used to drive the null space generation, and this is necessarily distinct from a solver that is preconditioned by MG.

Can you revert this change?

2021-12-16 23:30 UTC, maddyscientist requested changes
Thanks for this PR @jcosborn.  This is mostly ok, but the removal of `mg_inv_param` breaks the multigrid-preconditioned solver.

2021-12-17 15:18 UTC, maddyscientist approved these changes
Thanks for the reversion of the MG param @jcosborn.  I've confirmed this fixes the MG test again.  I fully intend to address the MG interface in the future.  I've pushed a slight change to make the deviation printing more consistent with other parts of QUDA.  Once Jenkins is finished, we can merge.

2021-12-17 17:30 UTC, merged