handle NULL input for host_evecs in eigensolveQuda
lattice/quda pull request #1379
Opened 2023-05-16 16:33 UTC by aniketsen

If eigenvectors are not required, `NULL` can be passed to `host_evecs` in `eigensolveQuda`, accordingly `ColorSpinorField`s are created with `QUDA_ZERO_FIELD_CREATE` instead of `QUDA_REFERENCE_FIELD_CREATE`.

2023-05-16 16:33 UTC, mathiaswagner commented
Jenkins: Can one of the admins verify this patch?

2023-05-16 16:33 UTC, mathiaswagner commented
Jenkins: Can one of the admins verify this patch?

2023-05-16 16:33 UTC, maddyscientist commented
@Jenkins ok to test

2023-05-19 01:40 UTC, maddyscientist requested changes
Thanks @aniketsen for this PR.  This looks good to me.  Juts a couple of minor changes needed:
* Apply clang-format
* delete white introduced on lines 2293 and 2294
* Feel free to add your name to the contributor list in the README

2023-05-23 21:24 UTC, maddyscientist approved these changes

2023-06-02 00:55 UTC, maddyscientist approved these changes

2023-06-02 00:55 UTC, merged