Feature/reproducible
lattice/quda pull request #1446
Opened 2024-03-18 23:20 UTC by maddyscientist

(this isn't ready to be merged, I'm creating this PR as a placeholder.)

2026-07-09 21:51 UTC, weinbe2 commented on include/kernels/gauge_fix_fft.cuh
> -      return operator()(data, value);
Has this been a long-standing bug that got missed in the unit testing?

2026-07-10 05:23 UTC, maddyscientist commented on include/kernels/gauge_fix_fft.cuh
> -      return operator()(data, value);
I'm not following the question here: what is the bug you're referring to here?

2026-07-10 16:14 UTC, weinbe2 commented on include/kernels/gauge_fix_fft.cuh
> -      return operator()(data, value);
The order of arguments---or did that convention get changed in this PR? I'm only a few files in, so I may have missed a systemic change.

2026-07-10 17:45 UTC, maddyscientist commented on include/kernels/gauge_fix_fft.cuh
> -      return operator()(data, value);
Ok, gotcha, now I understand the question.  The order didn't matter prior to this PR, as before now, the operands on the left and right are the same, e.g., both doubles, and the summation functor returns a double.  With the reproducible reductions (or Kahan in the future) the type on the left is a non-trivial type (i.e., `rfa_t`) and the type on the right is the simple scalar, with the functor returning an `rfa_t`.  The sum reduction functor is conceptionally `return data += value`, if that helps illustrate it better.

The compiler will complain about this, so the user won't do the wrong thing.

I did think about supporting having the non-trivial type as either the input operand, but I decided I prefer the logical consistency of mandating the non-trivial is the first operand.

2026-07-16 20:42 UTC, leonhostetler commented
I tried to compile this branch in the default configuration on DeltaAI (GH200), and it fails with errors:
```
include/dbldbl.h:382:31: error: expected type-specifier before '__float128'
include/register_traits.h:233:33: error: '__float128' was not declared in this scope; did you mean '_Float128'?
```
The root cause (according to Claude) is: `__float128` is a GCC extension type that only exists on x86/PowerPC. On aarch64, long double is already IEEE binary128, so GCC provides only `_Float128` (and does not define `__SIZEOF_FLOAT128__`). The quad-precision machinery is gated correctly behind `QUDA_USE_QUAD_SCALAR`, but two references escaped the gating and are compiled unconditionally in every configuration.

Claude recommended guarding the two offending sites with `#ifdef __SIZEOF_FLOAT128__`. If I do that, the default configuration builds cleanly, so I will proceed with eigensolver/deflation regression testing.

Separately, the quad configuration (`QUDA_SCALAR_TYPE=__float128`) is x86-only as written and on DeltaAI fails with `QUDA_SCALAR_TYPE=__float128 requires compiler support for __float128`.

2026-07-18 18:27 UTC, leonhostetler requested changes
I tested on 1 node on DeltaAI (GH200) using the default build configuration. I tested several workflows involving eigensolves and deflations. The eigensolves look fine, but the deflation breaks (see line-level comments). After implementing Claude's suggested fix, deflation works again, and I reproduce to expected precision the results obtained when I run the same tests with the develop branch.

2026-07-18 18:27 UTC, leonhostetler commented on include/reference_wrapper_helper.h
> +              std::enable_if_t<std::is_arithmetic_v<U> && !std::is_same_v<U, T> && !std::is_same_v<std::complex<U>, T>> * = nullptr>
This constructor captures `quda::vector<T> v(n)` whenever n is an integer type other than exactly `uint64_t`: it's an exact match, while `vector(uint64_t size, const T &value = {})` needs an integral conversion. The result is a length-1 vector holding n, not n elements — silently, with no diagnostic.
```
int bs = 2;
quda::vector<std::complex<double>> scales(bs);
// scales.size() == 1, scales[0] == (2,0)
```
This breaks `milc_interface.cpp:1424` (see comment there) resulting in heap corruption plus a silently wrong deflation space.

Claude suggests constraining to floating-point, which preserves the intent:
```
std::enable_if_t<std::is_floating_point_v<U> && !std::is_same_v<U, T> && !std::is_same_v<std::complex<U>, T>> * = nullptr>
```
(`!std::is_integral_v<U>` is equivalent. Making the size ctor explicit would be more robust but touches more call sites.) Claude's suggested fix resolves the heap corruption and silently wrong deflation space. An alternative would be to fix at the call site by casting `bs` to `uint64_t`, but that would leave the hazard(?) in place.

2026-07-18 18:27 UTC, leonhostetler commented on lib/milc_interface.cpp
> +      quda::vector<complex_t> scales(bs);
`bs` is `int`, so this now selects the new arithmetic-scalar constructor added in `reference_wrapper_helper.h:558` rather than the size constructor — `scales` ends up length 1 holding `bs`. Line 1425 then writes `bs` elements into it (heap overflow, confirmed by valgrind), and `blas::axy` on 1426 gets a length-1 scale vector, so the reconstructed second-parity eigenvectors are mis-normalized.

2026-07-21 15:59 UTC, weinbe2 commented on include/kernels/gauge_fix_fft.cuh
> -      return operator()(data, value);
This makes sense. I always assumed that it was strictly interpretted as `return data += value;`, which is why I was confused when the order changed. It's clear why it didn't matter in the past, but it does matter now. I support mandating the order.Thanks @maddyscientist !

2026-07-21 20:27 UTC, hummingtree reviewed
Additional correctness and build-configuration findings from the extended-precision / reproducible-reduction review.

2026-07-21 20:27 UTC, hummingtree commented on lib/eig_block_trlm.cpp
> +          return sr_norm;
Should this remain `quda::fabs(sr_norm)`? For SR, Ritz values can be negative; returning the signed value makes the locking/convergence threshold negative, so a nonnegative residual can never satisfy the test. This also changes the previous behavior.

2026-07-21 20:27 UTC, hummingtree commented on lib/deflation.cpp
> +  using MatrixXc = Matrix<complex_t, Dynamic, Dynamic>;
In a quad build this alias makes both `SelfAdjointEigenSolver<MatrixXc>` calls below operate on `complex<__float128>`. `eigen_helper.h` explicitly notes that Eigen returns incorrect eigenvectors for this type and introduces `eig_solve_complex_t` to keep projected solves in double. Should these deflation solves use that conversion path as well?

2026-07-21 20:27 UTC, hummingtree commented on lib/inv_eigcg_quda.cpp
> +   using DenseMatrix     = EigMatrixXcd;
This makes the EigCG projected eigensolves use `complex<__float128>` in a quad build, despite `eigen_helper.h` documenting that Eigen’s extended-precision eigenvectors are incorrect. Could we convert `Tm`/`H2k` to `eig_solve_complex_t`, solve in double, and convert the rotation coefficients back, as the other eigensolvers now do?

2026-07-21 20:27 UTC, hummingtree commented on include/dbldbl.h
> +  if (a.head() >= b.head()) {
The first comparison needs to be strict here. As written, equal heads return true without considering the tails, so `(1, -1) >= (1, 0)` is incorrectly true. This should be `a.head() > b.head()`, followed by the equal-head tail comparison. The same issue exists in `operator<=` below.

2026-07-21 20:27 UTC, hummingtree commented on include/eigen_quad_scalar.h
> +      return quda::eigen_fp128_pow(static_cast<__float128>(2), static_cast<__float128>(16384));
`2^16384` is outside the finite binary128 range, so `highest()` returns `+inf` and `lowest()` returns `-inf`. Eigen’s `NumTraits` expects the largest/smallest finite values here. Can these return the binary128 finite maximum and its negative instead?

2026-07-21 20:27 UTC, hummingtree commented on include/targets/cuda/reproducible_floating_accumulator.hpp
> +  __host__ __device__ ReproducibleFloatingAccumulator& operator-=(const ReproducibleFloatingAccumulator &other){
This overload currently has two issues when instantiated: `other` is const but unary `operator-()` is not const, and the function is missing `return *this;`. Could we make unary minus const and return the accumulator here?

2026-07-21 20:27 UTC, hummingtree commented on lib/CMakeLists.txt
> +set_property(CACHE QUDA_REDUCTION_ALGORITHM PROPERTY STRINGS NAIVE KAHAN REPRODUCIBLE)
`KAHAN` is exposed as a supported cache value, but selecting it reaches `kahan_t<reduction_t>` in `float_vector.h`, and there is currently no `kahan_t` definition. That makes an advertised configuration fail to compile. Should KAHAN be removed or rejected at configure time until it is implemented?

2026-07-21 20:30 UTC, hummingtree approved these changes
It looks nice and clean! I have left some comments (not really - codex did it) ...

2026-07-23 21:14 UTC, weinbe2 commented on include/kernels/blas_3d.cuh
> +      const complex<real> res = innerProduct(x, y);
Should the cast to `compute_t` happen before the call to `innerProduct`? Put differently, case `x` and `y` in some appropriate way (I'm not sure how casts of `Vector` would work, more specifically, if `ColorSpinor<real, Arg::nColor, Arg::nSpin>;` can be cast to `ColorSpinor<compute_t, Arg::nColor, Arg::nSpin>;`...)

2026-07-23 21:16 UTC, weinbe2 commented on include/kernels/multi_reduce_core.cuh
> +        for (int k=0; k < x.size(); k++) sum = plus<reduce_t>::apply(sum, dot_<compute_t>(x[k], y[k]));
This type of cast before sum is what I was considering in my comment in `blas_3d.cuh`

2026-07-23 21:17 UTC, weinbe2 commented on include/targets/cuda/reduce_helper.h
> -        // reset the atomic counter - this allows multiple calls to complete with ReduceArg construction
Is there a reason this comment was dropped?

2026-07-23 21:21 UTC, weinbe2 commented on include/blas_helper.cuh
> +            errorQuda("QUDA_PRECISION=%d does not enable real_t precision", QUDA_PRECISION);
This might be an accidental global find/replace mishap, I think this should still be `double`.

2026-07-23 21:26 UTC, weinbe2 commented on include/float_vector.h
>      T diff;
Not particularly important, but for cleanliness should we change these `T` -> `value_type`?

2026-08-03 21:47 UTC, weinbe2 commented on lib/momentum.cu
> +      force_stream << fname << "\t" << std::setprecision(5) << double(force[0]) << "\t"
Technically out of scope for this PR, but I say we add a quality-of-life improvement and update this to `logQuda` or something of that sort.

2026-08-07 18:04 UTC, weinbe2 commented on tests/host_reference/dslash_reference.cpp
>        double l2r = sqrt(nrm2 / src2);
Should this be `auto` instead of `double`?

2026-08-07 18:08 UTC, weinbe2 commented on tests/blas_test.cpp
> +      blas::axy(b, yH, zH);
Was this to exactly match the ordering within the QUDA device-side call? I'm impressed it required this much care, if so...

2026-08-07 20:20 UTC, maddyscientist commented on tests/blas_test.cpp
> +      blas::axy(b, yH, zH);
That's exactly it.  Without this the rounding order means changes at the order of an ULP (single or double precision), which would wash out any quad precision level reduction tests.

2026-08-07 20:22 UTC, maddyscientist commented on lib/momentum.cu
> +      force_stream << fname << "\t" << std::setprecision(5) << double(force[0]) << "\t"
I think most (all?) I/O in QUDA is done using C++ file streams and not using C APIs, so the present use here is consistent with what we do elsewhere (e.g., the tsv files).

Or is there something I'm missing here?

2026-08-07 20:38 UTC, weinbe2 commented on lib/momentum.cu
> +      force_stream << fname << "\t" << std::setprecision(5) << double(force[0]) << "\t"
Ah, no, I just read it a bit too quickly and didn't realize this was writing to a file since that generally doesn't happen in any of the `*.cu` files iirc.

2026-08-07 21:00 UTC, maddyscientist commented on include/float_vector.h
>      T diff;
Claude tells me the usual convention is to use `T` inside the classes, and save `value_type` for external reference.  So I will leave as is.

2026-08-08 00:04 UTC, maddyscientist commented on include/kernels/blas_3d.cuh
> +      const complex<real> res = innerProduct(x, y);
21b898156a75d4dfb22aa578d51c0e8691f88b49 does what you want here.  Since the inner products are done at the site level first of all, there's no need to do full reproducible reduction within the site, so we only need to ensure the site reduction is done in appropriate precision.

2026-08-08 00:04 UTC, maddyscientist commented on include/targets/cuda/reduce_helper.h
> -        // reset the atomic counter - this allows multiple calls to complete with ReduceArg construction
c623087a2b28e225f1235e2025a544b1d2e2a7f7

2026-08-08 00:05 UTC, maddyscientist commented on include/blas_helper.cuh
> +            errorQuda("QUDA_PRECISION=%d does not enable real_t precision", QUDA_PRECISION);
f6b5ab4cb1487d9e98f5cc8d8c74fd4af4d1c3a8

2026-08-08 00:05 UTC, maddyscientist commented on tests/host_reference/dslash_reference.cpp
>        double l2r = sqrt(nrm2 / src2);
f6b5ab4cb1487d9e98f5cc8d8c74fd4af4d1c3a8

2026-08-10 20:33 UTC, weinbe2 commented
From our convo offline, this line of code: https://github.com/lattice/quda/blob/feature/reproducible/include/kernels/gauge_utils.cuh#L26

Needs `double` -> `real_t` for the anisotropy argument.

2026-08-11 00:18 UTC, maddyscientist commented on lib/eig_block_trlm.cpp
> +          return sr_norm;
I see this issue have already been cleaned up by @leonhostetler with #1646 so I won't touch that here.

2026-08-12 00:40 UTC, maddyscientist commented on lib/inv_eigcg_quda.cpp
> +   using DenseMatrix     = EigMatrixXcd;
With Eigen now working with `__float128` I've cleaned all this up, so we should good on this front now.  All use of Eigen for the eigensolvers now uses `real_t` / `complex_t` consistently.  0d7fa7523ebd6bb23cc978e74d69c8fdaa15c575 is where this was done.

2026-08-12 00:41 UTC, maddyscientist commented on lib/deflation.cpp
> +  using MatrixXc = Matrix<complex_t, Dynamic, Dynamic>;
Cleaned up with 0d7fa7523ebd6bb23cc978e74d69c8fdaa15c575

2026-08-12 00:41 UTC, maddyscientist commented on include/dbldbl.h
> +  if (a.head() >= b.head()) {
8c6a7f8c43d6337159d7d9f6406d9ddd16b689f8

2026-08-12 00:42 UTC, maddyscientist commented on include/targets/cuda/reproducible_floating_accumulator.hpp
> +  __host__ __device__ ReproducibleFloatingAccumulator& operator-=(const ReproducibleFloatingAccumulator &other){
45ea5fced40f1779622199bc9c0c9ef26620cf97

2026-08-12 00:42 UTC, maddyscientist commented on lib/CMakeLists.txt
> +set_property(CACHE QUDA_REDUCTION_ALGORITHM PROPERTY STRINGS NAIVE KAHAN REPRODUCIBLE)
f6d94726654ef0f1b8f299976703bdc252e23ca3 rejects at configure time.

2026-08-12 00:45 UTC, maddyscientist commented on include/eigen_quad_scalar.h
> +      return quda::eigen_fp128_pow(static_cast<__float128>(2), static_cast<__float128>(16384));
thanks for pointing out this bug.  f6d94726654ef0f1b8f299976703bdc252e23ca3 fixes this.

2026-08-12 00:47 UTC, maddyscientist commented
Commenting that 5498137d8f536b875d340c06263f25eb74e4bff9 fixed the fundamental issue with Eigen with quad precision, namely that `isSigned` wasn't being correctly defined leading to Eigen assuming it was an unsigned type, leading to badness.  With that fixed, Eigen is absolutely fine now with quad precision.

2026-08-12 00:48 UTC, maddyscientist commented
> From our convo offline, this line of code: https://github.com/lattice/quda/blob/feature/reproducible/include/kernels/gauge_utils.cuh#L26
> 
> Needs `double` -> `real_t` for the anisotropy argument.

2830ba57981f215fd7c1d8e1a0453e1bd523c599 addresses this issue.  It wasn't a case of `double` needing to be switched for `real_t`, rather for the local template type `Arg::real`.  Issue now fixed though.

2026-08-19 05:07 UTC, maddyscientist commented on include/reference_wrapper_helper.h
> +              std::enable_if_t<std::is_arithmetic_v<U> && !std::is_same_v<U, T> && !std::is_same_v<std::complex<U>, T>> * = nullptr>
Fixed with 7b3bd339170932583c26bde64b258413a97ad978

2026-08-19 05:07 UTC, maddyscientist commented on lib/milc_interface.cpp
> +      quda::vector<complex_t> scales(bs);
Fixed with 7b3bd339170932583c26bde64b258413a97ad978

2026-08-19 05:20 UTC, maddyscientist commented
> I tried to compile this branch in the default configuration on DeltaAI (GH200), and it fails with errors:
> 
> ```
> include/dbldbl.h:382:31: error: expected type-specifier before '__float128'
> include/register_traits.h:233:33: error: '__float128' was not declared in this scope; did you mean '_Float128'?
> ```
> 
> The root cause (according to Claude) is: `__float128` is a GCC extension type that only exists on x86/PowerPC. On aarch64, long double is already IEEE binary128, so GCC provides only `_Float128` (and does not define `__SIZEOF_FLOAT128__`). The quad-precision machinery is gated correctly behind `QUDA_USE_QUAD_SCALAR`, but two references escaped the gating and are compiled unconditionally in every configuration.
> 
> Claude recommended guarding the two offending sites with `#ifdef __SIZEOF_FLOAT128__`. If I do that, the default configuration builds cleanly, so I will proceed with eigensolver/deflation regression testing.
> 
> Separately, the quad configuration (`QUDA_SCALAR_TYPE=__float128`) is x86-only as written and on DeltaAI fails with `QUDA_SCALAR_TYPE=__float128 requires compiler support for __float128`.

Thanks for point this out @leonhostetler.  Somewhat of an oversight on my part to not have tested it on Arm CPUs.  I have addressed this issue now:
* QUDA now uses an abstracted type `quda::float128_t` that is either `__float128` on x86-64 or `_Float128` on ARM
* This requires separate abstraction for the host math library since the `__float128` and `_Float128` have differently named functions, e.g., `sqrtq` vs `__builtin_sqrtf128`
* All use of `float128_t` should now be guarded by the preprocessor and hidden if quad-precision is not enabled
* When configuring QUDA, we can specify either `_Float128`, `__float128` or `float128` regardless of the platform when setting `QUDA_SCALAR_TYPE`
* I have verified that quad precision is working fine on Grace-Hopper, with a full build fully passing ctest

2026-08-20 22:42 UTC, weinbe2 commented on include/kernels/dslash_mdw_fused.cuh
>          kappa = -(c * (4. + m_5) - 1.) / (b * (4. + m_5) + 1.); // This is actually -kappa in my(Jiqun Tu) notes.
Should this get the `const real four = 4.0;` treatment like the other DWF files, or are we safe because `m_5` and `b` have already been cast? Am I correct in assuming that the problem in the other DWF files is how the `b_5`/`c_5` arrays aren't already cast to `real`?

2026-08-20 22:48 UTC, maddyscientist commented on include/kernels/dslash_mdw_fused.cuh
>          kappa = -(c * (4. + m_5) - 1.) / (b * (4. + m_5) + 1.); // This is actually -kappa in my(Jiqun Tu) notes.
Exactly as you say it, there's no issues here since every variable on this line is already a `real`, e.g., `double` or `float`.  C++ doesn't mandate that we cast double precision constants, e.g., the `4.0` to float and things just work.  One might argue that explicitly casting the constants to `real` would be desirable, e.g., if a custom precision type is used in future for field-local computations, but this is a pre-existing condition and not something to worry about right now (else it would be a further wide edit QUDA codebase).

2026-08-20 22:59 UTC, weinbe2 commented on include/blas_helper.cuh
> +            errorQuda("QUDA_PRECISION=%d does not enable real_t precision", QUDA_PRECISION);
Pedantic, but I believe this is an erroneous `double` -> `real_t` replacement (as are the other `diff` in this file)

2026-08-20 23:42 UTC, weinbe2 commented on lib/eigensolve_quda.cpp
> +    case QUDA_DOUBLE_PRECISION: logQuda(QUDA_VERBOSE, "Running eigensolver in real_t precision\n"); break;
`real_t` -> `double` in the `logQuda`

2026-08-20 23:45 UTC, maddyscientist commented on lib/eigensolve_quda.cpp
> +    case QUDA_DOUBLE_PRECISION: logQuda(QUDA_VERBOSE, "Running eigensolver in real_t precision\n"); break;
12216a8

2026-08-20 23:45 UTC, maddyscientist commented on include/blas_helper.cuh
> +            errorQuda("QUDA_PRECISION=%d does not enable real_t precision", QUDA_PRECISION);
12216a8

2026-08-20 23:59 UTC, weinbe2 commented on lib/inv_gmresdr_quda.cpp
> -    blas::legacy::caxpy(static_cast<Complex *>(Alpha.data()), vm, vkp1);
Should this also be changed to `reinterpret_cast`, like the updates above?

2026-08-21 00:08 UTC, weinbe2 commented on lib/pgauge_det_trace.cu
> +    complex_t &result;
I think this should remain an `array<double, 2>`; it's two separate values (determinant and trace), not a complex number. I have no issues with the variable renames otherwise, though.

2026-08-21 00:09 UTC, weinbe2 commented on lib/pgauge_det_trace.cu
> +    complex_t &result;
Nevermind I'm actually an idiot, it is indeed a complex, this is just confusing.

2026-08-21 00:21 UTC, weinbe2 approved these changes
Pending a few uninteresting comments, I approve of this PR. Thanks for the awesome work @maddyscientist !

2026-08-21 00:59 UTC, maddyscientist commented on lib/inv_gmresdr_quda.cpp
> -    blas::legacy::caxpy(static_cast<Complex *>(Alpha.data()), vm, vkp1);
None of this casting was actually necessary so I've just nuked it (and in general one should always prefer `static_cast` over `reinterpret_cast`).

2026-08-22 14:02 UTC, leonhostetler approved these changes
Great addition to QUDA!

2026-08-22 14:33 UTC, merged