Interface for Yang-Mills gradient flow
lattice/quda pull request #1480
Opened 2024-07-09 22:54 UTC by aniketsen

Implemented an interface for Yang-Mills gradient flow (arXiv:1302.5246, Appendix D). Uses existing kernels for Wilson flow and Laplace operator. Added a function `GFlowStep` to perform individual sub-steps of the Wilson flow. For this purpose, moved `WFlowStepType` to `enum_quda` to make it globally accessible.

2024-07-11 05:40 UTC, maddyscientist commented
@Jenkins ok to test

2024-07-13 11:27 UTC, maddyscientist requested changes
Thanks for this contribution @aniketsen, an excellent addition to QUDA.  I've left a few review comments, and a few things need fixed, but all should be easy to do.

Can you also apply clang-format to the diff please, as described [here](https://github.com/lattice/quda/wiki/Coding-Conventions-and-Style)?

Do you have any thoughts on how we can correctness tests for this (as well as the regular Wilson Flow function) in QUDA?  Short of fully implementing Wilson flow in a separate test code, is there anything that makes sense for testing?

2024-07-13 11:27 UTC, maddyscientist commented on include/gauge_tools.h
> +     @param[out] dataDs Output smeared field
I see there are typos in the doxygen here, inherited from the typos in `WFlowStep` above.  Can you this these?  E.g., 
```
     @param[out] dataDs Output smeared field
```
should be
```
     @param[out] out Output smeared field
```

2024-07-13 11:27 UTC, maddyscientist commented on lib/interface_quda.cpp
> +  GaugeField *precise = nullptr;
Now that the `GaugeField` class has copy and move constructors and assignment operators, there's no need to make this heap allocated (a pointer).  Can you make this an object?

While there's plenty of legacy QUDA that uses pointers, going forward, new code should use stack based allocation where possible.

2024-07-13 11:27 UTC, maddyscientist commented on lib/interface_quda.cpp
> +  ColorSpinorParam cudaParam(cpuParam, *inv_param, QUDA_CUDA_FIELD_LOCATION);
Probably I prefer `deviceParam` or something else that doesn't state `cuda` in its name.  Now that QUDA is portable, we should be saving the use of the CUDA word for target-specific things.

2024-08-21 09:56 UTC, aniketsen commented
@maddyscientist sorry for taking so long to get back. I have made the changes that you suggested.

For testing, we have a native cpu implementation which both the interfaces for Wilson flow and Gradient flow have been tested against. For a correctness test for Wilson flow, I don't see any other way than implementing the individual steps. For the Gradient flow, if the Wilson flow steps and ApplyLaplace are tested, the rest is just algebra, which I suppose is also separately tested.

2024-08-29 22:09 UTC, cpviolator commented
@maddyscientist @aniketsen That reminds me to implement some CPU code for (at least) the 3-staple action Stout and APE routines. I can get to that relatively soon if I find time away from my day job. Please leave it with me and I'll either make a separate PR or attach to this if it's not merged before I'm done.

2024-10-08 11:42 UTC, maddyscientist commented
cscs-ci run

2024-10-08 11:43 UTC, maddyscientist approved these changes

2024-10-10 08:43 UTC, merged